module.exports = {
  someSidebar: {
    ["Getting Started"]: [
      "introduction",
      "theme-builder",
      "quick-start",
      "release-notes",
      "migrate",
    ],
    ["Guides"]: [
      "handle-item-click",
      "add-keyboard-shortcut",
      "disable-boundaries-check",
      "disable-prevent-default-onkeydown",
      "render-anything",
      "disable-or-hide",
      "track-menu-visibility",
      "handling-multiple-menu",
      "set-a-custom-position",
      "how-to-style",
      "change-submenu-arrow",
      "disable-hide-submenu",
      "prevent-menu-from-closing",
      "usage-with-portal",
      "trigger-the-menu-outside-of-react-compoent",
    ],
    ["API Reference"]: [
      "api/menu",
      "api/item",
      "api/separator",
      "api/submenu",
      "api/use-context-menu",
      "api/context-menu",
    ],
  },
};
